#!/usr/bin/bash
export log_prefix=world_collision
export marg1=1
export marg2=1
export marg3=2
export marg4=4
export c1x2_constant_move_list="1 1 1 3 1 3 1 4 2 4  0 50 50 0 50 150 150 50 50 100 100 50 0 100 100 0"
export c1x3_constant_move_list="1 2 1 4 1 5 1 4 2 4"
exec ./test_monster "$@"
